config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get '/about', to: "pages#about"
  get '/contact', to: "pages#contact"
  get '/myblog/:id', to: "posts#blog", as: "myblog"
  patch '/posts/:id/edit', to: "posts#update", as: "update"
  get '/stories', to: "pages#stories"
  delete '/post/:id', to: 'posts#destroy', as: 'delete', method: :delete 
  resources :posts do
    resources :comments
  end
  
  devise_for :mes
   root 'pages#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :name, presence: true
end

app/models/me.rb
class Me < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  	def self.search(search)
    # where(:title, query) -> This would return an exact match of the query
    	where("title ILIKE ?", "%#{search}%") 
    	
    
  	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	  

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to myblog_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to posts_path(@post)
	end

	def show
	end 

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def stories
  end 
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def blog
    set_params
  end 

  def index
    if params[:search]
      @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order('created_at DESC')
    end 
  end 

  def new
  	@post = Post.new
  end 


  def create
  	@post = Post.new(post_params)
  	if @post.save
  		redirect_to myblog_path(@post), alert: "Post Created!"
  	else 
  		render :new
  	end 
  end 

  def show
  	set_params
  end 

  def edit
  	set_params
  	
  end 
  def update
    set_params
    if @post.update (params[:post].permit(:title, :body, :author, :image))
      redirect_to myblog_path 
    else
      render 'edit'
    end 
  end 

  def destroy
  	set_params
  	@post.destroy
  	redirect_to posts_path, alert: "Post deleted"
  end 


  private 
  def post_params
  	params.require(:post).permit(:title, :body, :author, :image)
  end 

  def set_params
  	@post = Post.find(params[:id])
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<h5 class="comment_name"><strong><%= comment.name %>: </strong> <%= comment.body %> <% if me_signed_in? %>
			|| <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: { confirm: 'Are you sure?' } %> 
				<% end %>
		</h5> 
		<!--  <%= time_ago_in_words(comment.created_at) %> Ago ) -->
		
 	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<h5><%= f.text_field :name, placeholder: "Your name (required)" %> </h5>
	<h4><%= f.text_area :body, placeholder: "Comment" %> </h4>
	<%= button_tag(type: 'submit', class: "btn btn-success") do %>
 Post
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>



<head>
    <head>
      <title>Zieh Blog</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>
<body>

	<!-- <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="mainheader">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"><%= link_to 'Home', new_post_path%></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                   <% if flash[:notice] %>
		       			 <li class="notice"><%= notice %></li>
		      		<% end %>
		      		<% if flash[:alert] %>
		        		<li class="alert"><%= alert %></li>
		      		<% end %>
		      
		     		<li><%= link_to 'About', about_path %></li>
		     		<li><%= link_to 'Blogs', posts_path%></li>
		     		<li><%= link_to 'Contact', contact_path%></li>

			   		<% if me_signed_in? %>
			     		<li><%= link_to 'Log out', destroy_me_session_path,  method: :delete %></li>
			      		<li><%= link_to 'Sign up', new_me_registration_path %></li>
			      		<li><%= link_to 'Login', me_session_path %></li>
		     		<% end %>
                    <li class="search-box"><%= form_tag(posts_path, :method => "get",  id: "search-form") do %>
                        <%= text_field_tag :search, params[:search], placeholder: "search ..." %>
                        <i class="icon-search"></i>
                    <% end %> 
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav> 
    	<!-- Page Header -->
    <header class="intro-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>The Sky Dancer</h1>
                        <hr class="small">
                        <span class="subheading"> </span>
                    </div>
                </div>
            </div>
        </div>
    </header>   
    </div> 

    		
<%= yield %>


        <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="social-media">
                        <ul class="list-inline text-center">
                            <li>
                                <a href="https://www.facebook.com/zieh.doma"><%= image_tag("facebook.png", :alt => "rss feed")%>
                                </a>
                            </li>
                            <li>
                                <a href="#"><%= image_tag("twitter.png", :alt => "rss feed") %>
                                </a>
                                
                            </li>
                            <li>
                                <a href="https://www.linkedin.com/in/dhamzee-sherpa-29b8b080
"><%= image_tag("linked-in.png", :alt => "rss feed") %>
                                </a>
                                    <span class="fa-stack fa-lg">
                                        <i class="fa fa-circle fa-stack-2x"></i>
                                        <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <p class="copyright text-muted">Copyright &copy; www.ziehdoma.com</p>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>

app/views/mes/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/pages/about.html.erb
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>A wandering soul, always in search of something/someone who inspires, lets me grow and be the best I can be. I Identify as a Buddhist, a "semi-active" Buddhist practioner to be precise, in the sense, Buddhism is a part of my culture. Tibetan Buddhism, it's history and it's mystical world  fasinates me.</p>

                <p>Hi, I am Dhamtsik Doma. You can call me Zieh(Zee) if that's easier to pronounce. A strong aries, passionate about life and learning, I see the world as an open learning institute AND I believe everything that moves, sits, passes by have a lesson to teach and one can learn a lot by just being mindful of one's surroundings.</p>

                <p>Lately, I have discovered the fun world of coding. When I am not working, I am usually in front of my computer, listening to music from around the world, coding, sometimes watching dog vidoes on youtube or foreign movies without subtitles or playing guitar. </p>

                <p>On this site, you will find my words, thoughts, experiences, stories, observations and anything that I find interesting to share with the world. Welcome.</p>
            </div>
        </div>
    </div>

    <hr>

app/views/pages/blog.html.erb
<header class="intro-header" style="background-image: url('img/post-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>Man must explore, and this is exploration at its greatest</h1>
                        <h2 class="subheading">Problems look mighty small from 150 miles up</h2>
                        <span class="meta">Posted by <a href="#">Start Bootstrap</a> on August 24, 2014</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
     
                    <h2 class="section-heading"><%= @post.title%></h2>

                    <p> <%= @post.body %></p>
                </div>
            </div>
        </div>
    </article>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

app/views/pages/contact.html.erb
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p> If you have any questions for me or would like to get in touch, please send me a message here.</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div> 

app/views/posts/_form.html.erb
<hr>
<div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">                
				<% if current_me %>
					<h2>Enter and submit a post below:</h2>
						<%= form_for @post, html: {multipart: true} do |f| %>
							<p><%= f.text_field :title, placeholder: "Enter post title" %> </p>
							<p><%= f.text_area :body, placeholder: "Enter post body" %> </p>
							<p><%= f.text_field :author, placeholder: 'author' %> </p>
							 <%= f.file_field :image %>
							<%= f.submit class: "btn btn-success"%>
							<br>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
			</div>
		</div>
</div>

app/views/posts/blog.html.erb
<article>   
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    
                    <h2><%=@post.title%></h2></br> 
                    <hr>
                    <%= image_tag (@post.image.url :medium)%>
                    <p><%=@post.body %></p>
                    <p>By:<%=@post.author%></p>
                    <% if me_signed_in? %>
                        <h5> <%= link_to "Edit", edit_post_path(@post.id) %> ||
                        <%= link_to "Delete", delete_path(@post.id), method: :delete, data:{ deletable: true} %> </h5>
                    <%end %>
                    <h5>Comments:</h5>
                    <h> <%= render @post.comments %> </h5>
                    <hr>
                    <%= render 'comments/form' %>
                   
                    <hr>
                </div>
            </div>
        </div>

        
 </article>

 
      

app/views/posts/edit.html.erb
<%= render 'posts/form' %>

app/views/posts/index.html.erb
	<% @posts.each do |post| %> 
	<article>	
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                	
             		<h2><%= link_to post.title %></h2>
                    <h5><%= post.created_at.to_date.strftime("%m/%d/%Y") %></h5></br> 
					<hr>
					<p><%= post.body.truncate(250)%><%= link_to "read more", myblog_path(post.id)%></p>
					<h4>By:<%= post.author%></h4>  
                    <% if me_signed_in? %>
                    <h5> <%= link_to "Edit", edit_post_path(post.id) %> ||

                    <%= link_to "Delete", delete_path(post.id), method: :delete, data:{ deletable: true} %></h5>
                    <%end %>
                    <hr>
                </div>
            </div>
        </div>
        

    </article>
    <% end %>
   

app/views/posts/new.html.erb
<%= render 'posts/form' %>

app/views/posts/show.html.erb
<article>   
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    
                    <h1><%= @post.title %>></h1>
                    <h6><%= link_to "Edit", edit_post_path %> ||

					<%= link_to "Delete", delete_path(@post), method: :delete, data:{ deletable: true} %></h6>
                    <%= image_tag (@post.image.url :medium) %></br>
					<p> <%= @post.body %></p>
					<h6>By: <%= @post.author %></h6>
					
					<hr>
                    <hr>
                </div>
            </div>
        </div>

        
 </article>